global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "nginx-prometheus-exporter"
    static_configs:
      - targets: ["localhost:8405"]
  - job_name: "kafka-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["$EXPORTERHOST:8080"]